config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :users do
    collection do
      get :signup
    end
  end
  root 'products#index'
  resources :products do
    get 'shipping_method', on: :collection
    get 'category_middle', on: :collection
    get 'category_bottom', on: :collection
  end
  resources :buys
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  acts_as_tree order: 'name'
  has_many :products
end

app/models/delivery_date.rb
class DeliveryDate < ApplicationRecord
  has_many :products
end

app/models/delivery_fee_owner.rb
class DeliveryFeeOwner < ApplicationRecord
  has_many :products
  has_many :shipping_methods
end

app/models/image.rb
require 'carrierwave/storage/abstract'
require 'carrierwave/storage/file'
require 'carrierwave/storage/fog'
class Image < ApplicationRecord
  mount_uploader :image, ImagesUploader
  belongs_to :product, optional: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :images
  accepts_nested_attributes_for :images
  belongs_to :delivery_fee_owner
  belongs_to :shipping_method
  belongs_to :delivery_date
  belongs_to :category
  belongs_to :size
  validates :name, presence: true

  enum status: {  '新品未使用': 1, '未使用に近い': 2, '目立った傷や汚れなし': 3,
                 'やや傷や汚れあり': 4, '傷や汚れあり': 5, '全体的に状態が悪い': 6 }
  enum shipping_from: {
    '北海道': 1, '青森': 2, '岩手': 3, '宮城': 4, '秋田': 5, '山形': 6, '福島': 7,
      '茨城': 8, '栃木': 9, '群馬': 10, '埼玉': 11, '千葉': 12, '東京': 13, '神奈川': 14,
      '新潟': 15, '富山': 16, '石川': 17, '福井': 18, '山梨': 19, '長野': 20,
      '岐阜': 21, '静岡': 22, '愛知': 23, '三重': 24,
      '滋賀': 25, '京都': 26, '大阪': 27, '兵庫': 28, '奈良': 29, '和歌山': 30,
      '鳥取': 31, '島根': 32, '岡山': 33, '広島': 34, '山口': 35,
      '徳島': 36, '香川': 37, '愛媛': 38, '高知': 39,
      '福岡': 40, '佐賀': 41, '長崎': 42, '熊本': 43, '大分': 44, '宮崎': 45, '鹿児島': 46,
      '沖縄': 47, '未定': 48
  }
end

app/models/shipping_method.rb
class ShippingMethod < ApplicationRecord
  has_many :products
  belongs_to :delivery_fee_owner
end

app/models/size.rb
class Size < ApplicationRecord
  acts_as_tree order: 'size'
  has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :address, dependent: :destroy
  # accepts_nested_attributes_for :address
end

app/controllers/address_controller.rb
class AddressController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth, if: :production?
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :birth_year, :birth_month, :birth_day, address_attributes: [:first_name, :last_name, :first_name_phon, :last_name_phon]])
  end

  private

  def production?
    Rails.env.production?
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/buys_controller.rb
class BuysController < ApplicationController

  def index

  end
  def show
    @product = Product.find(params[:id])
    @products = Product.order("created_at ASC").limit(3)
  end

  def new

  end
  def create

  end
  def edit

  end

  def update

  end
  def destroy

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.order("created_at ASC").limit(4)
  end

  def show

  end

  def new
    @sell = Product.new
    @shipping_method = ShippingMethod.new
    @categories = Category.eager_load(children: :children).where(parent_id: nil)
    @image = Image.new
  end

  def create
    @sell = Product.new(sell_params)

    if @sell.save! & save_images(@sell, image_params)
      redirect_to product_path(@sell)
    else
      redirect_to root_path
    end
  end

  def edit
    @sell = Product.find(params[:id])
    @image = @sell.images
  end

  def update
    @sell = Product.find(params[:id])
    if @sell.update(sell_params)
      redirect_to product_path(@sell)
    else
      redirect_to root_path
    end
  end

  def shipping_method
    @sell = Product.new
    render partial: 'sells/shipping_method', locals: { delivery_fee_owner_id: params[:delivery_fee_owner_id] }
  end

  def category_middle
    @categories = Category.roots.find(params[:parent_id])
  end
  def category_bottom
    @categories = Category.roots.find(params[:top_id]).children.find(params[:parent_id])
  end

  private

  def sell_params
    params.require(:product).permit(:delivery_fee_owner_id, :shipping_method_id,:delivery_date_id, :name, :info, :price, :status,
                                    :size_id, :category_id, :shipping_from, :brand)
  end

  def image_params
    params.require(:images).require(:image).permit(params[:images][:image].keys) if params[:images].present?
  end

  def save_images(item, images)
    if images.present?
      return false if item.id.blank?
      images.values.each do |name|
        @image = item.images.create(image: name)
      end
    else
      @image_error = "画像がありません"
      return false
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def signup
  end

  def show
    @products = Product.order("created_at ASC")
  end
end

app/helpers/address_helper.rb
module AddressHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buys_helper.rb
module BuysHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/buys/_buy-content_confirm.html.haml
%main.single-main
  %section.single-container
    .buy-container
      %h2.single-container__head
        購入を確定しますか？
      %section.buy-content
        .buy-content__inner
          %h3.buy-content__item-image.buy-item
            = image_tag "https://static.mercdn.net/thumb/photos/m82884941197_1.jpg?1541928495"
            %p.buy-content__item-name.bold
              Cisco ASA(5505) 、CD等の付属品アリ
            = form_with url:root_path, class:"buy-content__form" ,local:true do |f|
              //金額もサーバーサイドができたら反映させる
              .buy-content__price-ja.bold
                ¥ 25,000
                %span.buy-content__shipping-fee.bold
                  送料込み
              //サーバサイドができたらポイントの有無で条件分岐させる
              %ul.buy-content__point.not-have
                .buy-content__point_parent
                  .buy-content__point_parent-toggle
                    ポイントはありません
              //hidden属性で商品情報データを埋め込みpostする
              %ul.buy-content__price-table
                %li.buy-content__price-row.bold
                  .buy-content__price-cell
                    支払い金額
                  .buy-content__price-cell 
                    17,800   
              = button_tag "購入する",class:"btn-default btn-red bold"
      %section.buy-content.buy-content__user-info
        .buy-content__inner.h3
          %h3 配送先
          %address.buy-content__user-info-text
            〒231-0023
            %br
            神奈川県 横浜市中区
            山下町247-2
            武内ビル 503
            %br
            林 悠暉
          %p.buy-content__user-info-text
          = link_to "https://www.mercari.com/jp/transaction/address/m33016370175/",class:"buy-content__user-info-fix" do 
            変更する
            %i.fa.fa-angle-right
      %section.buy-content.buy-content__user-info
        .buy-content__inner.h3
          %h3 支払い方法
          %p.buy-content__user-info-text
            ************0004
            %br
            12 / 20
          %figure
            = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?1355968437"
            = link_to "https://www.mercari.com/jp/transaction/address/m33016370175/",class:"buy-content__user-info-fix" do
              変更する
              %i.fa.fa-angle-right




      

app/views/buys/_item-detail-message.html.haml
.item-detail-message
  .masseges
    .other-massege
      .other-massege__icon
        =link_to do
          %img{ :src => 'https://public.potaufeu.asahi.com/4e91-p/picture/13545647/061f1eeff8bb2432950152393bddf7cb.jpg', :class => 'other-massege__icon__image'}
          %p 出品者
      .other-massege__right
        .other-massege__right__name
          若林正恭
        .other-massege__right__box
          .other-massege__right__box__text
            こんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわ
          .other-massege__right__box__bottom
            .other-massege__right__box__bottom__date
              .far.fa-clock
              130日前
            .other-massege__right__box__bottom__flag
              = link_to do
                .far.fa-flag

    .my-massege
      .my-massege__icon
        =link_to do
          %img{ :src => 'https://public.potaufeu.asahi.com/4e91-p/picture/13545647/061f1eeff8bb2432950152393bddf7cb.jpg', :class => 'other-massege__icon__image'}
          %p 出品者
      .my-massege__left
        .my-massege__right__name
          若林正恭
        .my-massege__right__box
          .my-massege__right__box__text
            こんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわこんちわ
          .my-massege__right__box__bottom
            .my-massege__right__box__bottom__date
              .far.fa-clock
              130日前
            .my-massege__right__box__bottom__dustbox
              = link_to do
                .fa.fa-trash-alt

  .item-detail-message__attention
    相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
  .item-detail-message__input
    %textarea
  .item-detail-message__btn
    %button コメントする

app/views/buys/_item-details.html.haml
.items-box-container
  .item-details
    .item-details__name
      %h1
        = @product.name
    .item-details__main
      .item-details__main__photo
        .item-details__main__photo__top
          = image_tag @product.images.first.image.to_s, class: 'item-details__main__photo__top__image'
        .item-details__main__photo__sub
          - @product.images.each do |image|
            = image_tag image.image.to_s, class: 'item-details__main__photo__sub__image'
      .item-details__main__table
        %table
          %tbody
            %tr
              %th 出品者
              %td
                =link_to "a", user_path
                .item-user-ratings
                  .item-user-ratings__list
                    %i.fas.fa-laugh
                    %span 114
                  .item-user-ratings__list
                    %i.fas.fa-meh
                    %span 3
                  .item-user-ratings__list
                    %i.fas.fa-frown
                    %span 1
            %tr
              %th カテゴリー
              %td
                .category
                  = link_to products_path ,class: "category__magin-bottom" do
                    = @product.category.root.name

                .category
                  = link_to  products_path ,class: "" do
                    .fas.fa-chevron-right
                    = @product.category.parent.name
                .category
                  = link_to products_path,class: "" do
                    .fas.fa-chevron-right
                    = @product.category.name
            %tr
              %th ブランド
              %td= @product.brand
            %tr
              %th 商品のサイズ
              %td= @product.size.size
            %tr
              %th 商品の状態
              %td= @product[:status]
            %tr
              %th 配送料の負担
              %td= @product.delivery_fee_owner.delivery_fee_owner
            %tr
              %th 配送の方法
              %td= @product.shipping_method.shipping_method
            %tr
              %th 配送元地域
              %td
                =link_to @product[:shipping_from]
            %tr
              %th 発送日の目安
              %td= @product.delivery_date.delivery_date
    .item-details__price
      .item-details__price__main= "¥#{@product.price}"
      .item-details__price__tax
        (税込)
      .item-details__price__shipping-fee
        送料込み
    %button.item-details__btn-red
      購入画面に進む
    / ⬆︎current-userだったら表示しない
    .item-details__description
      - if @product.info
        = @product.info
      - else
        商品の説明はありません
    .item-details__button
      .item-details__button__left
        %button
          .far.fa-heart
          いいね！
          １
        %button
          .far.fa-flag
          不適切な商品の報告
      .item-details__button__right
        .fas.fa-lock
        =link_to "あんしん・あんぜんへの取り組み"
    / ⬆︎current-userだったら表示しない

app/views/buys/_items-in-user-profile.html.haml
.items-in-user-profile
  .items-in-user-profile__category
  %a{ :href => '', :class => 'items-in-user-profile__category__name'}
    カワさんのその他の出品
  - @products.each do |product|
    = render partial: "products/item", locals: { product: product }
  .items-in-user-profile__category
  %a{ :href => '', :class => 'items-in-user-profile__category__name'}
    カーディガン （メンズ） その他の商品
  - @products.each do |product|
    = render partial: "products/item", locals: { product: product }

app/views/buys/_nav-item-link.html.haml
.nav-item-link
  .nav-item-link__left
    = link_to do
      .fas.fa-chevron-left
      ユニフレーム バーベキューグリル
  .nav-item-link__right
    = link_to do
      .fas.fa-chevron-right
      しろさん専用ダウンコート

app/views/buys/new.html.haml
.single-container
  = render 'users/shared/single-header'
  = render 'buy-content_confirm'
  = render 'users/shared/single-footer'

app/views/buys/show.html.haml
.default-container
  = render 'products/top-header.html.haml'

  = render 'item-details'
  = render 'item-detail-message'
  = render 'nav-item-link'
  = render partial:'users/social-media-box'
  = render 'items-in-user-profile'

  = render 'products/app-vanner.html.haml'
  = render 'products/top-footer.html.haml'