config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :users do
    collection do
      get :signup
    end
  end
  root 'products#index'
  resources :products do
    get 'shipping_method', on: :collection
    get 'category_middle', on: :collection
    get 'category_bottom', on: :collection
  end
  resources :buys
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  acts_as_tree order: 'name'
  has_many :products
end

app/models/delivery_date.rb
class DeliveryDate < ApplicationRecord
  has_many :products
end

app/models/delivery_fee_owner.rb
class DeliveryFeeOwner < ApplicationRecord
  has_many :products
  has_many :shipping_methods
end

app/models/image.rb
require 'carrierwave/storage/abstract'
require 'carrierwave/storage/file'
require 'carrierwave/storage/fog'
class Image < ApplicationRecord
  mount_uploader :image, ImagesUploader
  belongs_to :product, optional: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :images
  accepts_nested_attributes_for :images
  belongs_to :delivery_fee_owner
  belongs_to :shipping_method
  belongs_to :delivery_date
  belongs_to :category
  belongs_to :size
  validates :name, presence: true

  enum status: {  '新品未使用': 1, '未使用に近い': 2, '目立った傷や汚れなし': 3,
                 'やや傷や汚れあり': 4, '傷や汚れあり': 5, '全体的に状態が悪い': 6 }
  enum shipping_from: {
    '北海道': 1, '青森': 2, '岩手': 3, '宮城': 4, '秋田': 5, '山形': 6, '福島': 7,
      '茨城': 8, '栃木': 9, '群馬': 10, '埼玉': 11, '千葉': 12, '東京': 13, '神奈川': 14,
      '新潟': 15, '富山': 16, '石川': 17, '福井': 18, '山梨': 19, '長野': 20,
      '岐阜': 21, '静岡': 22, '愛知': 23, '三重': 24,
      '滋賀': 25, '京都': 26, '大阪': 27, '兵庫': 28, '奈良': 29, '和歌山': 30,
      '鳥取': 31, '島根': 32, '岡山': 33, '広島': 34, '山口': 35,
      '徳島': 36, '香川': 37, '愛媛': 38, '高知': 39,
      '福岡': 40, '佐賀': 41, '長崎': 42, '熊本': 43, '大分': 44, '宮崎': 45, '鹿児島': 46,
      '沖縄': 47, '未定': 48
  }
end

app/models/shipping_method.rb
class ShippingMethod < ApplicationRecord
  has_many :products
  belongs_to :delivery_fee_owner
end

app/models/size.rb
class Size < ApplicationRecord
  acts_as_tree order: 'size'
  has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :address, dependent: :destroy
  # accepts_nested_attributes_for :address
end

app/controllers/[scope]/unlocks_controller.rb
# frozen_string_literal: true

class [scope]::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/address_controller.rb
class AddressController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth, if: :production?
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :birth_year, :birth_month, :birth_day, address_attributes: [:first_name, :last_name, :first_name_phon, :last_name_phon]])
  end

  private

  def production?
    Rails.env.production?
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/buys_controller.rb
class BuysController < ApplicationController

  def index

  end
  def show
    @product = Product.find(params[:id])
    @products = Product.order("created_at ASC").limit(3)
  end

  def new

  end
  def create

  end
  def edit

  end

  def update

  end
  def destroy

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.order("created_at ASC").limit(4)
  end

  def show

  end

  def new
    @sell = Product.new
    @shipping_method = ShippingMethod.new
    @categories = Category.eager_load(children: :children).where(parent_id: nil)
    @image = Image.new
  end

  def create
    @sell = Product.new(sell_params)

    if @sell.save! & save_images(@sell, image_params)
      redirect_to product_path(@sell)
    else
      redirect_to root_path
    end
  end

  def edit
    @sell = Product.find(params[:id])
    @image = @sell.images
  end

  def update
    @sell = Product.find(params[:id])
    if @sell.update(sell_params)
      redirect_to product_path(@sell)
    else
      redirect_to root_path
    end
  end

  def shipping_method
    @sell = Product.new
    render partial: 'sells/shipping_method', locals: { delivery_fee_owner_id: params[:delivery_fee_owner_id] }
  end

  def category_middle
    @categories = Category.roots.find(params[:parent_id])
  end
  def category_bottom
    @categories = Category.roots.find(params[:top_id]).children.find(params[:parent_id])
  end

  private

  def sell_params
    params.require(:product).permit(:delivery_fee_owner_id, :shipping_method_id,:delivery_date_id, :name, :info, :price, :status,
                                    :size_id, :category_id, :shipping_from, :brand)
  end

  def image_params
    params.require(:images).require(:image).permit(params[:images][:image].keys) if params[:images].present?
  end

  def save_images(item, images)
    if images.present?
      return false if item.id.blank?
      images.values.each do |name|
        @image = item.images.create(image: name)
      end
    else
      @image_error = "画像がありません"
      return false
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def signup
  end

  def show
    @products = Product.order("created_at ASC")
  end
end

app/helpers/address_helper.rb
module AddressHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buys_helper.rb
module BuysHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_app-vanner.html.haml
.app-vanner
  .app-vanner__image
    .app-vanner__content
      %h2.app-vanner-h
        スマホでかんたんフリマアプリ
      %p.app-vanner-p
        今すぐ無料ダウンロード！
      %ul.app-vanner__content__store
        %li.app-vanner__content__store-li
          = image_tag '/mercari_icon.png', class: 'mercari-icon'
        %li.app-vanner__content__store-li
          = link_to 'https://www.apple.com/jp/ios/app-store/', class: 'pull-left' do
            = image_tag '/app-store.svg'
        %li.app-vanner__content__store-li
          = link_to 'https://play.google.com/store?hl=ja', class: 'pull-left' do
            = image_tag '/google-play.svg'
    = image_tag'/mercari-app.png', class: 'app-vanner__right'

app/views/products/_item.html.haml
= link_to(buy_path(product.id)) do
  .item-box
    - if product.images.present?
      = image_tag product.images.first.image_url.to_s, class: 'item-box__image'
    .item-box__name
      = product.name
    .item-box__price
      ¥
      = product.price
    .item-box__tax
      (税込)

app/views/products/_picup-container.html.haml
.picup-container
  %h2.picup-container-header
    ピックアップカテゴリー
  .picup-container__item
    = link_to '', class: 'picup-container__name' do
      レディース新着アイテム
    - @products.each do |product|
      = render partial: "item", locals: { product: product }
    = link_to '', class: 'picup-container__last' do
      すべての商品を見る
  .picup-container__item
    = link_to '', class: 'picup-container__name' do
      レディース新着アイテム
    - @products.each do |product|
      = render partial: "item", locals: { product: product }
    = link_to '', class: 'picup-container__last' do
      すべての商品を見る

app/views/products/_sell-content.html.haml
%main.single-main
  %section.sell-container
    .sell-container__inner
      %h2.single-container__head
        商品の情報を入力
      = form_with model: sell,class:"sell-container__form", local:true do |f|
        .sell__upload-box
          %h3.sell__upload-box_head
            出品画像
            %span.sell__upload-box_form.form-require
              必須
          %p 最大10枚までアップロードできます
          .sell-upload.clearfix
            .sell-upload__items-container
              .sell-upload__items
                %ul
              .sell-upload__items
                %ul
            .sell-upload__drop-box.have-item-0#file-upload
              = f.fields_for @image, sell.images.build do |f|
                = f.file_field :image,name: 'images[image][0]',id:'file',style:"display: none;"
              %pre.visible-pc#btn
                ドラッグアンドドロップ
                またはクリックしてファイルをアップロード
                %i.fa.fa-camera{style:"display: none;"}
        .sell-content
          .sell-content__name_form.form-group.bold
            = f.label "商品名"
            %span.sell-content__name_require.form-require
              必須
            = f.text_field :name,class: "sell-content__input input-default", placeholder: "商品名（必須 40文字まで)"
          .sell-content__desc.form-group.bold
            = f.label "商品の説明"
            %span.sell-content__desc_require.form-require
              必須
            = f.text_area :info,class:"sell-content__desc_textarea textarea-default",rows:"5" ,placeholder:"商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
        .sell-content.clearfix
          %h3.sell-content__detail-head.sub-head 商品の詳細
          .sell-content__detail.form-box.bold
            .sell-content__detail_form.form-group
              = f.label "カテゴリー"
              %span.sell-content__detail_require.form-require
                必須
              .sell-content__select-wrap#category-top
                = f.select :category_id, options_from_collection_for_select( Category.roots.sort, :id, :name),{prompt: "---"},class:"sell-content__select-default"
                %i.fas.fa-chevron-down
              .sell-content__select-wrap#category-middle
              .sell-content__select-wrap#category-bottom
            .sell-content__detail_form.form-group.display-none#size
              = f.label "サイズ"
              %span.sell-content__detail_require.form-require
                必須
              .sell-content__select-wrap
                = f.collection_select :size_id, Size.roots.find(1).children,:id, :size, {prompt: "---"},{class:"sell-content__select-default",id:"size"}
                %i.fas.fa-chevron-down.fa-2x
            .sell-content__detail_form.form-group.no-margin.display-none#brand
              = f.label "ブランド"
              %span.sell-content__detail_require.form-option
                任意
              .sell-content__select-wrap
                = f.text_field :brand,class: "sell-content__input input-default"
            .sell-content__detail_form.form-group
              = f.label "商品の状態"
              %span.sell-content__detail_require.form-require
                必須
              .sell-content__select-wrap
                = f.select :status, Product.statuses.keys, {prompt: "---"}, class: "sell-content__select-default"
                %i.fas.fa-chevron-down.fa-2x
        .sell-content.clearfix
          %h3.sell-content__delivery-head.sub-head 配送について
          = link_to "?","https://mercari.com/jp/help_center/article/68/",target:"_blank",class:"form-question"
          .sell-content__delivery.form-box.bold
            .sell-content__delivery_form_wrap.form-group
              .sell-content__delivery_form
                = f.label "配送料の負担"
                %span.sell-content__delivery_require.form-require
                  必須
              .sell-content__select-wrap
                = f.collection_select :delivery_fee_owner_id, DeliveryFeeOwner.all,:id, :delivery_fee_owner, {prompt: "---"},{class:"sell-content__select-default",id:"delivery_fee_owner"}
                %i.fas.fa-chevron-down.fa-2x
            .sell-content__delivery_form_wrap.form-group#shipping_method.display-none
              .sell-content__delivery_form
                = f.label "配送の方法"
                %span.sell-content__delivery_require.form-require
                  必須
              .sell-content__select-wrap.shipping-method
                = render partial: 'shipping_method',locals: {f:f,delivery_fee_owner_id: DeliveryFeeOwner.first.id}
                %i.fas.fa-chevron-down.fa-2x
            .sell-content__delivery_form_wrap.form-group
              .sell-content__delivery_form
                %label
                  発送元の地域
                  %span.sell-content__delivery_require.form-require
                    必須
                .sell-content__select-wrap
                  = f.select :shipping_from, Product.shipping_froms.keys, {prompt: "---"}, class: "sell-content__select-default"
                  %i.fas.fa-chevron-down.fa-2x
            .sell-content__delivery_form_wrap.form-group
              .sell-content__delivery_form
                %label
                  発送までの日数
                  %span.form-require
                    必須
                .sell-content__select-wrap
                  = f.collection_select :delivery_date_id, DeliveryDate.all,:id, :delivery_date, {prompt: "---"},{class:"sell-content__select-default",id:"delivery_date"}
                  %i.fas.fa-chevron-down.fa-2x
        .sell-content.clearfix
          %h3.sell-content__price-head.sub-head 販売価格(300〜9,999,999)
          = link_to "?","https://mercari.com/jp/help_center/article/68/",target:"_blank",class:"form-question"
          .sell-content__price.form-box
            %ul.sell-content__price-list
              %li.sell-content__price-list_form.form-group.bold
                .clearfix
                  = f.label "価格"
                  %span.sell-content__price_require.form-require
                    必須
                  .l-right.sell-content__price_input
                    ¥
                    = f.text_field :price, class:"input-default",placeholder:"例）300"
              %li.clearfix
                .l-left
                  販売手数料 (10%)
                .l-right
                  #charge
                    \-
              %li.clearfix.bold
                .l-left
                  販売利益
                .l-right
                  #profit
                    \-
        .modal{role:"dialog", tabindex:"-1"}
          .modal-inner
        .sell-content.sell-contents__sell-btn-box
          .sell-content__sell-btn-box
            %p
              = link_to "禁止されている出品","https://www.mercari.com/jp/help_center/getting_started/prohibited_items/"
              、
              = link_to "行為","https://www.mercari.com/jp/help_center/getting_started/prohibited_conduct/"
              を必ずご確認ください。
            %p
              またブランド品でシリアルナンバー等がある場合はご記載ください。
              = link_to "偽ブランドの販売","https://www.mercari.com/jp/help_center/getting_started/counterfeit_goods/"
              は犯罪であり処罰される可能性があります。
            %p
              また、出品をもちまして
              = link_to "加盟店規約","https://www.mercari.com/jp/seller_terms/"
              に同意したことになります。
          = f.submit "出品する" ,class:"sell-content__btn-red"
          .sell-content__btn-gray
            もどる

app/views/products/_sell-item-change-box.html.haml
.items-box-container
  .sell-item-change-box
    %button.sell-item-change-box__btn-red
      商品の編集
    %p.sell-item-change-box__text
      or
    %button.sell-item-change-box__btn-gray
      出品を一旦停止する
    %button.sell-item-change-box__btn-gray
      この商品を削除する

app/views/products/_top-footer.html.haml
.top-footer__wrap
  .top-footer
    .top-footer__about-mercari
      .top-footer__title メルカリについて
      .top-footer__company-profile 会社概要（運営会社）
      .top-footer__privacy-policy プライバシーポリシー
      .top-footer__terms-of-Service メルカリ利用規約
      .top-footer__point-contract メルカリ利用規約・有償ポイントに関する特約
      .top-footer__smartphone-support あんしんスマホサポート制度に関する利用特約
      .top-footer__compliance-policy コンプライアンスポリシー
      .top-footer__management-of-personal-data 個人データの安全管理に係る基本方針
      .top-footer__specific-commercial-transactions 特定商取引に関する表記
      .top-footer__fund-settlement-law 資金決済法に基づく表示
      .top-footer__deterrence-of-crime 法令順守と犯罪抑止のために
      .top-footer__adoption 採用情報
    .top-footer__view-mercuri
      .top-footer__title メルカリを見る
      .top-footer__category カテゴリー一覧
      .top-footer__brand ブランド一覧
      .top-footer__area 出品地域一覧
      .top-footer__blog 公式ブログ
      .top-footer__twitter 公式Twitter
      .top-footer__facebook 公式Facebook
    .top-footer__help
      .top-footer__title ヘルプ＆ガイド
      .top-footer__guide メルカリガイド
      .top-footer__logo-guidelines メルカリロゴ利用ガイドライン
      .top-footer__notice お知らせ
      .top-footer__rakuraku-bin らくらくメルカリ便とは
      .top-footer__yuuyuu-bin ゆうゆうメルカリ便とは
      .top-footer__big-rakuraku-bin 大型らくらくメルカリ便とは
      .top-footer__car-dealing 車体取引ガイド
      .top-footer__refund 返品・返金ポリシー
      .top-footer__declaration メルカリあんしん・あんぜん宣言！
      .top-footer__fake-brand 偽ブランド品撲滅への取り組み
      .top-footer__mercari-box メルカリボックス
    .top-footer__country
      .top-footer__title 国
      .top-footer__USA
        = image_tag("/flag_us.png", class: :"top-footer__icon")
        .top-footer__name United States
      .top-footer__UK
        = image_tag("/flag_uk.png", class: :"top-footer__icon")
        .top-footer__name United Kingdom
      .top-footer__JPN
        = image_tag("/flag_jp.png", class: :"top-footer__icon")
        .top-footer__name 日本
    .top-footer__logo
      = image_tag("/logo-white.svg", class: :"top-footer__logo__image")
      .top-footer__copyright &copy; 2019 Mercari

app/views/products/_top-header.html.haml
.top-header
  .clearfix
    = link_to root_path do
      = image_tag("/mercari-sign-up.svg", class: :"top-header__logo")
    .top-header__form
      = form_tag(" /products/search", method: :get)
      = text_field_tag :text, '', placeholder: 'キーワードから探す', name: 'keyword',class: 'form__input'
      = button_tag '', class: "form__button fa fa-search", value: "&#xf002"
  .clearfix
    .top-header__search-link
      .search-link--category カテゴリから探す
      .search-link--brand ブランドから探す
    .top-header__user-info
      - if user_signed_in?
        .user-info__mypage
          = link_to  destroy_user_session_path, method: :delete do
            ログアウト
            / とりあえずのログアウトボタンです。ログアウトボタンを他のところでつけると思うのでその時に消します。
          = link_to "/users/#{current_user.id}" do
            = image_tag("/mypage.png", class: :"mypage__image")
            .mypage__title マイページ
          .user-info__notice
            .fa.fa-bell
            .notice__text お知らせ
          .user-info__todo
            .fa.fa-check
            .todo__text やることリスト
      - else
        .user-info__mypage
          %ul.user-info__information
            %li.user-info__signin
              = link_to new_user_session_path, class: 'user-info__link' do
                .user-info__box1
                  ログイン
            %li.user-info__signup
              = link_to signup_users_path, class: 'user-info__link' do
                .user-info__box1
                  新規会員登録

app/views/products/_top-main-vidual.html.haml
.slick
  .top-main-vidual
    .top-main-vidual__one
      .top-main-vidual__content
        %h2.top-main-vidual-h
          スマホでかんたん
          %br
          フリマアプリ
        %p.top-main-vidual-p
          メルカリはスマホカメラからすぐに出品できる
          %br
          購入時も安心な独自アプリです
        %ul.top-main-vidual__store
          %li.top-main-vidual__li
            = link_to 'https://www.apple.com/jp/ios/app-store/', class: 'pull-left' do
              = image_tag '/app-store.svg'
          %li.top-main-vidual__li
            = link_to 'https://play.google.com/store?hl=ja', class: 'pull-left' do
              = image_tag '/google-play.svg'
      = image_tag '/top-main-vidual-content-right.png', class: 'top-main-vidual__right'
  .top-main-vidual
    .top-main-vidual__two
      = image_tag '/mercari0309.jpg', class: 'top-main-vidual__image'
  .top-main-vidual
    .top-main-vidual__three
      = image_tag '/merukari-old.png', class: 'top-main-vidual__image'

app/views/products/category_bottom.js.erb
$('#category-bottom').html('<%= j(select :product,:category_id,options_from_collection_for_select(@categories.children.sort, :id, :name),{prompt: "---"},{class:"sell-content__select-default"})%>');
$('#category-bottom').append(`<i class="fas fa-chevron-down">`);

app/views/products/category_middle.js.erb
$('#category-middle').html('<%= j(select :product,:category_id,options_from_collection_for_select(@categories.children.sort, :id, :name),{prompt: "---"},{class:"sell-content__select-default"})%>');
$('#category-middle').append(`<i class="fas fa-chevron-down">`);

app/views/products/edit.html.haml
.single-container
  = render 'users/shared/single-header'
  = render partial: 'sell-content',locals: {sell:@sell}
  = render 'users/shared/single-footer'

app/views/products/index.html.haml
= render 'top-header.html.haml'
= render 'top-main-vidual'
= render 'picup-container'
= render 'app-vanner.html.haml'
= render 'top-footer.html.haml'

app/views/products/new.html.haml
.single-container
  = render 'users/shared/single-header'
  = render partial: 'sell-content',locals: {sell:@sell}
  = render 'users/shared/single-footer'

app/views/products/show.html.haml
.single-container
  = render 'products/top-header'
  = render 'buys/item-details'
  = render 'sell-item-change-box'
  = render 'buys/item-detail-message'
  = render 'products/app-vanner'
  = render 'products/top-footer'